In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.08385662, 0.05900859, 0.09237295, 0.0964194 , 0.10245769,
        0.11315079, 0.11891036, 0.13579595, 0.11490085, 0.08312683]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.09837733, 0.09596297, 0.09921872, 0.09962102, 0.10022438,
        0.10130183, 0.10188697, 0.103622  , 0.10147928, 0.09830556]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.289651

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1126 - accuracy: 0.9657
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0902 - accuracy: 0.9721
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0752 - accuracy: 0.9766
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0658 - accuracy: 0.9789
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0587 - accuracy: 0.9804


In [11]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0543 - accuracy: 0.9819
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0476 - accuracy: 0.9846
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0436 - accuracy: 0.9857
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0423 - accuracy: 0.9859
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0396 - accuracy: 0.9866
313/313 - 1s - loss: 0.0677 - accuracy: 0.9804 - 582ms/epoch - 2ms/step


[0.06769997626543045, 0.980400025844574]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533707, 0.08533707, 0.08533707, 0.08533924, 0.08533707,
        0.08533707, 0.08533707, 0.23196426, 0.08533707, 0.08533708],
       [0.08533686, 0.08533751, 0.23196757, 0.08533695, 0.08533686,
        0.08533686, 0.08533686, 0.08533686, 0.08533686, 0.08533686],
       [0.08534414, 0.2318523 , 0.08534478, 0.08534433, 0.08534422,
        0.08534417, 0.08534414, 0.08537769, 0.08536009, 0.08534414],
       [0.23196793, 0.08533682, 0.08533697, 0.08533682, 0.08533683,
        0.08533683, 0.08533683, 0.08533682, 0.08533682, 0.08533722],
       [0.08533832, 0.08533832, 0.08533833, 0.08533832, 0.23194453,
        0.08533832, 0.08533832, 0.08533899, 0.08533832, 0.08534831]],
      dtype=float32)>