In [1]:
import numpy as np

In [2]:
def cofactor(A, i, j):  # 여인수 계산
  (n,m) = A.shape
  M = np.zeros((n-1, m-1))
  for a in range(0, n-1):
    k = a if (a < i) else a+1
    for b in range(0, m-1):
      l = b if (b < j) else b+1
      M[a,b] = A[k,l]

  return (-1)**(i+j)*np.linalg.det(M)

In [3]:
def inverseByAdjointMatrix(A):  # 수반행렬을 이용한 A의 역행렬 계산
  detA = np.linalg.det(A)       # A의 행렬식 계산
  (n, m) = A.shape
  adjA = np.zeros((n,m))

  for i in range(0,n):          # 수반행렬생성
    for j in range(0,m):
      adjA[j,i] = cofactor(A, i, j)
  if detA != 0.0:
    return (1./detA) * adjA
  else:
    return 0

In [5]:
A = np.array([[-4, 0, 2 ,-1, 0], [1, 3, -3, -1, 4], [2, 0, 1, 3, 0], [-2, 1, -3, -1, 5], [1, -5, 1, 0, 5]])
print("A =", A)

Ainv = inverseByAdjointMatrix(A)
print("A inverse = ", Ainv)

A = [[-4  0  2 -1  0]
 [ 1  3 -3 -1  4]
 [ 2  0  1  3  0]
 [-2  1 -3 -1  5]
 [ 1 -5  1  0  5]]
A inverse =  [[-0.07321966  0.2106319  -0.03610832 -0.24573721  0.0772317 ]
 [ 0.16950853  0.26579739  0.09729188 -0.14343029 -0.06920762]
 [ 0.32397192  0.30090271  0.09127382 -0.35105316  0.11033099]
 [-0.05917753 -0.24072217  0.32698094  0.28084253 -0.08826479]
 [ 0.11935807  0.16349047  0.08625878 -0.02407222  0.09327984]]
