In [2]:
def calc(n):
  sum = 0
  for i in range(0,n):
    sum += int(input())
  return sum

print("Input the number of values to be added => ")
count = int(input())
while count <= 0:
  count = int(input())
print("Sum = ", calc(count))

Input the number of values to be added => 
5
1
2
3
4
5
Sum =  15


In [4]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([[1],
              [2],
              [3]])
print("A = ", A)
print("v = ", v)

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
v =  [[1]
 [2]
 [3]]


In [5]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([[1],
              [2],
              [3]])
print("A = ", A)
print("v = ", v)

print("A.shape =", A.shape)
print("v.shape =", v.shape)

w = np.array([1, 2, 3])
print("w =", w)
print("w.shape =", w.shape)

B = np.array([[1, 2, 3], [4, 5, 6]])
print("B =", B)
print("B.shape =", B.shape)

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
v =  [[1]
 [2]
 [3]]
A.shape = (3, 3)
v.shape = (3, 1)
w = [1 2 3]
w.shape = (3,)
B = [[1 2 3]
 [4 5 6]]
B.shape = (2, 3)
